services:
  backend:
    build:
      context: ./backend
    container_name: effective_mobile_backend
    expose:
      - "8080"
    networks:
      - effective_mobile_network

  nginx:
    image: nginx:stable-alpine
    container_name: effective_mobile_nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - effective_mobile_network

networks:
  effective_mobile_network:
    driver: bridge